### PR TITLE
Replace PNG images with SVG icons

### PR DESCRIPTION
**Pull request by frutiger**
### Motivation

On high-resolution displays, the 16x16 PNG icons render in very blurry manner. Thankfully, I was able to find MIT licensed icon sets for StarCraft leagues and races (https://github.com/nephest/sc2-icons) as well as for geographical regions (https://github.com/yammadev/flag-icons).

### Preview

Here is a preview of what this change looks like:
Screenshot 2020-07-19 at 13 43 44

### Implementation Notes

* Since the images are SVG, they require height/width to be specified for them to render correctly. I'm not sure if sprinkling the codebase with the width/height attributes is the preferred way to go here, or if you'd rather have them done in CSS.
* I also could not find an icon for "SEA" and ended up using Taiwan's flag. I wasn't actually sure about the "SEA" region as I couldn't find any reference to it in the Blizzard API documentation.
* I wasn't able to test every page of the site, some URLs would end up crashing the Python program for reasons I was unable to investigate; I believe these crashes are unrelated to the image changes.

Any feedback would be highly appreciated and thank you for considering this PR.

### CODE REVIEW

**Comment by andersroos** [comment]
Thank you for contributing.

I agree that using svg would be superior to png as they would render better on high resolution devices. However I do not think that the looks of these svgs are good enough.

* The race svgs looks ok but I very much prefer to use something that looks similar to what you see in game as it will be easier to understand. For example it is not obvious what the GM and master icons are if you don't see the others at the same time.

* The flag svgs looks blurry on low resolution, maybe there is too much detail in them. Also there is a light hue which makes them look bad on black background. 

* The race svgs looks good.

* Another problem is that the javascript generated graphs use image bitmaps to copy icons directly into the graph, this does no longer seem to work when using svgs (https://www.rankedftw.com/stats/races/1v1/#v=2&r=-2&l=-2, https://www.rankedftw.com/team/850017/#td=world&ty=c&ra=best&tyz=0&tx=a&tl=1). I am sure it is fixable, but maybe not spend time on it right now. Maybe it was on the pages that crashed for you. If you send me the stack trace I can help you figure out how to get things working.

* No need to find flags for SEA as the plan is to remove SEA from the site. Since Blizzard changed the terms and I was forced to delete old data there is no longer any SEA data left.

Maybe an alternative solution could be to use higher resolution versions of the pngs and let the browser scale them. I have higher resolution versions of the race and league icons (at least 120x120). Flags are probably the easiest to find. I do not think that setting dimensions in html are a problem, maybe it could be done in css though.

**Comment by frutiger** [comment]
Thank you for the feedback.

I do agree that the league icons are not all obvious (especially the master/grandmaster leagues). Unfortunately I could not find high-quality icons that are also suitably licensed. I specifically wanted to avoid extracting them from StarCraft II assets as there are potential copyright liabilities.

I did not get a chance to preview the icons/flags on the generated graphs (due to the aforementioned crash) and so hadn't noticed the problems against the dark background. I will spend a bit of time investigating before I send you the stack traces, as the problem may be purely on my end.

I will also see if I can emulate a low resolution display to reproduce the blurriness you are seeing with the flags. They do have a lot of detail and I can imagine that they won't render well on a low resolution display.

**Comment by frutiger** [comment]
I fixed the crash error I had (beginner mistake of linking against one Python version but running another) and I fixed the issue with the league icon sizes being too large. However I can see the problem you mentioned: there is not enough contrast with the background colours. I will search around to see if I can find alternate icon sets.

**Comment by andersroos** [comment]
Nice that you solved the python issue.

I don't think we need to replace all icons if we can't find any. If you find some good flags icons we can switch out the race icons and the flag icons leaving league as is for now.

**Comment by frutiger** [comment]
I was able to successfully emulate low-DPI displays, and I noticed that the region flags are indeed blurry. However, I was able to resolve all the other issues. I will be opening some new PRs to accommodate them.

**Pull request closed without merging**
